/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vfpBkDAaheA
 */
import { Button } from "@/components/ui/button"

export function Remote0() {
  return (
    <div className="flex flex-col items-center justify-center bg-gray-700 p-4 rounded-lg w-48">
      <div className="grid grid-cols-2 gap-2 mb-2 w-full">
        <Button className="mb-2 bg-red-600 text-white">Power</Button>
        <Button className="mb-2 bg-green-600 text-white">Menu</Button>
      </div>
      <div className="grid grid-cols-2 gap-2 mb-2 w-full">
        <Button className="bg-yellow-500 text-white">Flix</Button>
        <Button className="bg-red-500 text-white">Tube</Button>
      </div>
      <div className="flex justify-center items-center mb-2 w-full">
        <div className="flex flex-col">
          <Button className="mb-1 bg-gray-500 text-white">▲</Button>
          <div className="flex">
            <Button className="mr-1 bg-gray-500 text-white">◄</Button>
            <Button className="bg-gray-500 text-white">OK</Button>
            <Button className="ml-1 bg-gray-500 text-white">►</Button>
          </div>
          <Button className="mt-1 bg-gray-500 text-white">▼</Button>
        </div>
      </div>
      <div className="grid grid-cols-2 gap-2 mb-2 w-full">
        <Button className="bg-gray-500 text-white">▶</Button>
        <Button className="bg-gray-500 text-white">||</Button>
      </div>

      <div className="grid grid-cols-2 gap-2 mb-2 w-full">
        <Button className="bg-gray-500 text-white">Vol +</Button>
        <Button className="bg-gray-500 text-white">Vol -</Button>
      </div>
      <div className="grid grid-cols-2 gap-2 mb-2 w-full">
        <Button className="bg-gray-500 text-white">Ch +</Button>
        <Button className="bg-gray-500 text-white">Ch -</Button>
      </div>
    </div>
  )
}
